version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: bookclub-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build: ..
    container_name: bookclub-app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/bookclub
    volumes:
      - ..:/app
    restart: on-failure

volumes:
  mongo-data:
